name: frontend-ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Recupere le repo
        uses: actions/checkout@v4
      
      - name: Installe pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Installe Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml


      - name: Install toutes les dependances du projet
        run: pnpm install --frozen-lockfile

      - name: Installe Playwright avec ses dependances
        run: pnpm exec playwright install --with-deps

      - name: Lance ESLint
        run: pnpm lint

      - name: Test E2E
        run: pnpm test:e2e --update-snapshots

      - name: Build
        run: pnpm build